# Site settings
title: KDB Developer Career
description: KDB Developer Career
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KDB Developer
user_title: Software Developer
email: rlekqls12@kakao.com
github_username: rlekqls12

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
